[tool.isort]
profile = "black"
group-by-package = true
combine-as-imports = true
combine-star = true
known-third-party = ["PySide6", "pymongo"]
known-first-party = ["ClientSockets", "ServerSockets", "Database", "Shared"]
